kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubecontroller-csharp
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - myproject.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecontroller-csharp
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubecontroller-csharp
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubecontroller-csharp
subjects:
- kind: ServiceAccount
  name: kubecontroller-csharp
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubecontroller-csharp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubecontroller-csharp
    spec:
      serviceAccountName: kubecontroller-csharp
      containers:
      - name: kubecontroller-csharp
        image: suwatch01/kubecontroller-csharp:latest
